### ISSUE TITLE
lsm_grid_statistics

### ISSUE THREAD

**Issue by renatamuy** [mauriciovancine/lsmetrics#3]
ideias a partir de GenZonStats e lsm_grid_statistics:
-flexibilizar para qualquer shapefile (zonal stats) ao invés de v.mkgrid 
-permitir batch (zonais de um stack com vários rasters para um grid ou shapefile)

**Comment by mauriciovancine** [comment]
Oi Rê! Massa as ideias.

- pensei em outra função, algo como lsm_polygon_statistics(). Assim deixamos essa para funcionar apenas com grids. O que acha? Pensei em algo como um lsm_buffer_statistics(), para indicar um vetor de pontos e distância para buffers.
- aqui eu não fiz de propósito. Nenhum das funções do lsmetrics versão do Mau funcionam para mais de um raster por vez. Eu preferiria colocar num for para não dar erro.

Mas seria massa saber como o Ber tem pensado. 

Valeu!

**Comment by renatamuy** [comment]
Oi Mau, 
-blz!
-sim, for seria o ideal. Sim, vamos ver o que o Ber acha.

**Comment by mauriciovancine** [comment]
Eu add vcs dois a esse repositório. Mas acho que com o que temos, podemos migrar para o repositório do LEEC. Mas vou deixar essa missão para o Ber =]

**Comment by renatamuy** [comment]
Pode fechar esse issue, não?

**Comment by mauriciovancine** [comment]
Ops, agora que sim. Pode sim. Vou fechar.
